server:
  port: 8081 # Cambiado de 8080 a 8081
spring:
  application:
    name: "bck-aunthentication"
  devtools:
    add-properties: false
  r2dbc:
    url: "r2dbc:postgresql://aws-1-us-east-2.pooler.supabase.com:6543/postgres"
    username: "postgres.wefitfcbvdzujhexegyg"
    password: "pragma"
  profiles:
    include: null
adapters:
  r2dbc:
    host: "aws-1-us-east-2.pooler.supabase.com"
    port: 6543
    database: "postgres"
    schema: "public"
    username: "postgres.wefitfcbvdzujhexegyg"
    password: "pragma"
routes:
  paths:
    usuarios: "/api/v1/usuarios"
    usuariosById: "/api/v1/usuarios/{id}"
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8081" # Actualizado para incluir el nuevo puerto